version: '3'
services:
  server:
      image: prom/prometheus:v2.38.0
      volumes:
        - ./prometheus_server/prometheus.yml:/etc/prometheus/prometheus.yml
      network_mode: "host"

  exporter:
      build: ./prometheus_exporter
      network_mode: "host"